language: php

php:
  - 7.2.5

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - npm install

script:
  - php artisan key:generate
  - vendor/bin/phpunit